const sidebar = [
  {
    type: 'category',
    label: 'Start Here',
    collapsed: false,
    items: [
      'introduction/00-introduction',
      'introduction/architecture',
    'introduction/command-reference',
      'introduction/content-model',
      'introduction/references',
      'introduction/ux-and-accessibility',
      'introduction/learning-and-recovery-map',
      'introduction/roadmap',
    ],
  },
  {
    type: 'category',
    label: 'Installation',
    collapsed: false,
    items: [
      'preparation/01-preparation',
      'preparation/preflight',
      'installation-media/02-installation-media',
      'installation-media/download-and-verify',
      'boot/03-boot',
      'boot/live-environment',
      'network/04-network',
      'network/live-network',
      'network/networking-architecture',
      'network/wireless-and-network-recovery',
      'network/network-services-and-ssh',
      'network/vpn-and-remote-access',
      'storage/05-storage',
      'storage/partitioning',
      'storage/partition-and-format',
      'storage/filesystem-strategy',
      'storage/ssd-and-trim',
      'storage/luks-encryption-strategy',
      'storage/btrfs-snapshots-and-recovery',
      'storage/storage-recovery-drills',
      'installation/06-installation',
      'installation/installation-runbook',
      'installation/installation-decision-tree',
      'installation/verification-checklist',
      'installation/pre-reboot-gate',
      'installation/base-install',
      'system-configuration/07-system-configuration',
      'system-configuration/initramfs-and-microcode',
      'system-configuration/systemd-operations',
      'system-configuration/first-system-configuration',
      'bootloader/08-bootloader',
      'bootloader/bootloader-strategy',
      'bootloader/systemd-boot',
      'bootloader/boot-recovery',
    ],
  },
  {
    type: 'category',
    label: 'Post-Install',
    items: [
      'desktop/10-desktop',
      'desktop/desktop-strategy',
      'hardware/11-hardware',
      'hardware/hardware-inventory',
      'hardware/graphics-and-gpu',
      'hardware/power-management',
      'hardware/bluetooth-and-audio',
      'hardware/wayland-display-stack',
      'security/12-security',
      'security/security-baseline',
      'security/service-hardening',
      'security/secure-boot-with-sbctl',
      'security/firewall-baseline',
      'security/application-security',
      'security/accessibility-and-secure-input',
      'development/13-development',
      'development/development-environment',
      'development/git-and-ssh-workflow',
      'development/aur-and-package-builds',
      'development/containers-and-virtualization',
      'dual-boot/14-dual-boot',
      'dual-boot/windows-dual-boot-safety',
      'maintenance/15-maintenance',
      'maintenance/system-maintenance',
      'maintenance/backup-and-recovery-readiness',
      'maintenance/observability-and-performance',
    ],
  },
  {
    type: 'category',
    label: 'Troubleshooting & Recovery',
    items: [
      'troubleshooting/99-troubleshooting',
      'troubleshooting/boot',
      'troubleshooting/network',
      'troubleshooting/package-manager',
      'troubleshooting/display',
      'troubleshooting/hardware',
      'troubleshooting/recovery',
      'troubleshooting/systemd',
      'troubleshooting/storage',
    ],
  },
];

export default {handbook: sidebar};
