name: Link Check


permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          args: --verbose --no-progress "**/*.md"
